export const GET_AUTHOR_REQUEST = "GET_AUTHOR_REQUEST";
export const GET_AUTHOR_SUCCESS = "GET_AUTHOR_SUCCESS";
export const GET_AUTHOR_FAIL = "GET_AUTHOR_FAIL";
export const GET_AUTHOR_BOOKS_REQUEST = "GET_AUTHOR_BOOKS_REQUEST";
export const GET_AUTHOR_BOOKS_SUCCESS = "GET_AUTHOR_BOOKS_SUCCESS";
export const GET_AUTHOR_BOOKS_FAIL = "GET_AUTHOR_BOOKS_FAIL";
